FROM ubuntu:18.04
ENV DEBIAN_FRONTEND noninteractive
ENV INITRD No
ENV IPFS_PATH /home/ipfs-user/.ipfs

RUN apt-get update && \
    apt-get -y install git tor mongodb build-essential gcc make clang libpcap-dev python3-dev python3-pip python3 wget onioncat net-tools kmod iptables openjdk-8-jre-headless && \
    rm -rf /var/lib/apt/

RUN useradd -u 500 -ms /bin/bash ipfs-user

RUN wget http://dist.ipfs.io/go-ipfs/v0.4.17/go-ipfs_v0.4.17_linux-amd64.tar.gz && \
    tar zxf go-ipfs_v0.4.17_linux-amd64.tar.gz && \
    cd go-ipfs && \
    mv ipfs /usr/bin/ipfs && \
    chmod +x /usr/bin/ipfs && \
    cd / && \
    rm -rf go-ipfs && rm go-ipfs_v0.4.17_linux-amd64.tar.gz

RUN git clone https://github.com/robertdavidgraham/masscan && \
     cd masscan && \
     make -j && \
     mv bin/masscan /bin/masscan && \
     cd / && \
     rm -rf masscan

#RUN wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein && \
#    mv lein /usr/bin/lein && \
#    chmod a+x /usr/bin/lein && \
#    lein

RUN mkdir -p /dev/net && \
    mknod /dev/net/tun c 10 200

ADD ./src/backend/requirements.txt /src/backend/requirements.txt
RUN pip3 install -r /src/backend/requirements.txt

#ADD ./src/frontend /src/frontend

#RUN cd /src/frontend && \
#    lein deps && \
#    lein clean && \
#    lein package && \
#    mv /src/frontend/web /web && \
#    cd / && \
#    rm -rf /src/frontend

ADD ./scripts /scripts
RUN mkdir logs && chmod +x /scripts/docker-entrypoint.sh 
ADD ./default_config /default_config
ADD ./src/backend /src/backend
ADD ./assets /assets
CMD ["bash", "scripts/run.sh"]
